name: Build Android APK
on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get Date
      id: get-date
      run: |
        echo "date=$(date -u +'%Y%m%d')" >> $GITHUB_OUTPUT
      shell: bash

    - name: Cache Buildozer global directory
      uses: actions/cache@v4
      with:
        path: ~/.buildozer
        key: buildozer-global-${{ runner.os }}-${{ steps.get-date.outputs.date }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Build with Buildozer
      uses: ArtemSuts/buildozer-action@v1
      with:
        workdir: .
        buildozer_version: stable

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: package
        path: bin/*.apk

